@startuml C4_L1_BooksStore
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(annonymous, "Public user")
Person(user, "Authorized user")

System(booksStore, "Books store CMS")

System_Ext(authorization, "Authorization system", "For authorization purposes")
System_Ext(publisher, "Publisher system", "Giving details about books published by them")

Rel(annonymous, booksStore, "Interact", "Book records")
Rel(user, booksStore, "Interact", "Book records")

Rel(booksStore, authorization, "Gets user authorization")
Rel(booksStore, publisher, "Gets books information")

@enduml
