version: "3.9"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks: &ntKafaka
      - nt-kafka

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks: *ntKafaka

  app:
    image: node:18-alpine
    working_dir: /workspace
    command: yarn start
    volumes:
      - ./node_modules:/workspace/node_modules:ro
      - ./app.js:/workspace/app.js
      - ./package.json:/workspace/package.json
      - ./yarn.lock:/workspace/yarn.lock
    depends_on:
      - kafka
    networks: *ntKafaka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  nt-kafka:
